alpha: 1.0
batch_size: 64
fn: null
initial_sleep: 5
max_leaderboard_age: 3600
max_staleness: 60
run_step_interval: 1
max_success_staleness: 100
maxsize: 128
min_leaderboard_weight: 0
mode: thread
netuid: 0
network: local
print_interval: 100
sample_interval: 0.1
search: null
run_step_interval: 3
start: true
max_age: 1000 # the maximum age of the worker
threads_per_worker: 64 
timeout: 10 # timeout for the worker
timeout_info: 4 # the timeout for the info worker
verbose: false #
debug: false # This is the key that we need to change to true
vote_interval: 100 # the number of iterations to wait before voting
workers: 1 # the number of workers
run_loop: true # This is the key that we need to change to false
module_eval_keys : ['w', 'address', 'name', 'key', 'latency', 'staleness']
expected_info_keys : ['w', 'address', 'name', 'key']
score_fns : ['score_module', 'score'] # the score functions

