
# network
network: subspace # the network to connect to (bittensor, commune, local) to specify subnet, (subspace.0 or subspace.text)
netuid: null # (OPTIONAL) if you have a voting network with subnets [bittensor, commune]
sync_interval: 600
sample_interval: 0.005 # the sleep interval between sending samples
search: null # the search for modules in the namespace
fn : null # the function to filter

# epoch
mode: thread
batch_size: 32 # the batch size for the worker
workers: 1 # the number of workers
threads_per_worker: 32
timeout: 3
sleep_time: 0.05
refresh : True
start: True
is_main_worker: True
debug: False
min_update_interval: 30 # the minimum interval to update the network
alpha: 0.5 # the ma average
max_leaderboard_age: 3600 # the maximum age of the leaderboard 
max_history: 10


# run loop
initial_sleep : 5 # the initial sleep time before running the loop
print_interval: 5 # the sleep interval between sending samples
vote_interval: 100 # the interval to vote (in blocks (8 seconds per block))

# logging
verbose: True # the verbosity of the logging