
version: "3.9"
services:
  ganache:
    network_mode: host
    cpu_count: 2
    container_name: ganache
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MNEMONIC: ${GANACHE_MNEMONIC}
      WEB3_INFURA_PROJECT_ID: ${WEB3_INFURA_PROJECT_ID}
      WEB3_INFURA_URL: ${WEB3_INFURA_URL}
      WEB3_ALCHEMY_PROJECT_ID: ${WEB3_ALCHEMY_PROJECT_ID}
      WEB3_ALCHEMY_URL: ${WEB3_ALCHEMY_URL}
      PRIVATE_KEY: ${PRIVATE_KEY}
    volumes:
      - ${GANACHE_PATH}/scripts:/app/scripts
      

    restart: always
    command: bash -c "/app/scripts/setup.sh"

