[tool.poetry]
name = "commune"
version = "0.1.0"
description = "A library to connect all of the libraries"
authors = ["latentvector <you@example.com>"]
license = "CLOSED AI"
readme = "README.md"

[tool.poetry.scripts]
c = "commune.cli:main"

# configure autopep to not format type ignores !!!
[tool.autopep8]
ignore_local_config = true
aggressive = 2
in-place = true
recursive = true
max_line_length = 80
ignore = [
  "E265", # block comment should start with '# '
  "E501", # line too long
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
fastapi = "*"
sse-starlette = "*"# server sent events for streaming back to client
torch = "*"
msgpack_numpy = "*"
substrate-interface = "*"
paramiko = "*"
plotly = "*" # dope interactive plots
streamlit = "*" # dope for web apps
pytest = "*"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.examples]
optional = true

[tool.poetry.group.docs]
optional = true

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
testpaths = "./tests"
pythonpath = ["."]

[tool.pyright]
strict = ["src"]
# reportUnusedVariable = "warning"

[tool.ruff]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}