---
version: "2.1"
services:
  commune:
    build:
      context: ./commune
      dockerfile: Dockerfile
    container_name: commune
    shm_size: '1gb' # for the shared memory size
    volumes:
      - ~/.commune:/config/.commune
      - ./:/commune
      - /var/run/docker.sock:/var/run/docker.sock # allow for docker to talk to deamon in outside
    ports:
      # 
      - 50050-50250:50050-50250

    restart: unless-stopped