[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "commune"
version = "4.20.69"
description = "commune"
readme = "README.md"
authors = [{name = "commune", email = ""}]
license = "MIT"
homepage = "https://github.com/commune-ai/commune"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: IDGAF License, Do What You Want",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.8",
]
scripts = ["bin/c"]

[project.urls]
homepage = "https://github.com/commune-ai/commune"

[project.scripts]
c = "bin/c"

[project.requires-python]
python = ">=3.7"

[project.dependencies]
# Add your dependencies here. For example:
# numpy = "^1.21.2"
# pandas = "^1.3.3"

[project.optional-dependencies]
# Add your optional dependencies here. For example:
# test = ["pytest", "pytest-cov"]