
# network
network: subspace
netuid: 0 # optional if you have a voting network with subnets [bittensor, commune]
verbose: False
batch_size: 32
sync_interval: 100
sleep_interval: 5
search: null
max_staleness: 500

# score
alpha: 0.5

# voting 
vote: True
min_stake: 1
vote_interval: 200
vote_timeout: 50
min_count_before_vote: 100
voting_networks: ['subspace', 'bittensor']

# stats
max_history: 10

# score
connect_score: 0.1 
latency_score_weight: 0.2
alpha: 0.5 # the ma average
vote_tag : null 


# workers
mode: thread
num_workers: 1
threads_per_worker: 32
timeout: 10
sleep_time: 0.05
refresh : True
start: True
is_main_worker: True
min_num_weights: 10
debug: False
print_interval: 5
clone_suffix : clone







