

key : null
netuid: 0
module_prefix: null
network: main 
max_history: 10
alpha: 0.9
timeout: 10
tag: null
num_workers: 10
start: True
verbose: True
batch_size: 4
refresh_stats: True
vote_interval: 100
sync_interval: 1000
sleep_time: 1
vote: True
min_stake: 1
connect_score: 0.1 
max_staleness: 100


