

key : null
netuid: 0
module_prefix: model
network: main 
max_history: 10
alpha: 0.9
timeout: 2
tag: base
num_threads: 100
start: True
voting_interval: 100
verbose: False
batch_size: 4
refresh_stats: False
vote_interval: 10