

key : null
netuid: 0
module_prefix: null
network: main 
max_history: 10
alpha: 0.9
timeout: 2
tag: null
num_threads: 100
start: True
verbose: False
batch_size: 4
refresh_stats: False
vote_interval: 10
sleep_time: 1
min_stake: 1
connect_score: 0.1 
