
# network
chain: null
network: subspace
netuid: 0
voting_networks: ['subspace', 'bittensor']
threads_per_worker: 20
max_history: 10
alpha: 0.5
timeout: 4

tag: null
num_workers: 10
start: True
verbose: False
batch_size: 200
refresh_stats: False
vote_interval: 100
sync_interval: 100
search: null
batch_size: 16
max_staleness: 10
virtual_module: False
check_loop: True
run_mode : thread
run_loop: True
run_loop_sleep: 8

# voting 
vote: True
min_stake: 1
vote_interval: 200
vote_timeout: 50
timeout: 3
min_count_before_vote: 100

# stats
history_features: ['w', 'timestamp', 'latency']
max_history: 10
refresh_stats: False

# score
connect_score: 0.1 
latency_score_weight: 0.2
alpha: 0.5



# workers
timeout: 10
sleep_time: 0.05
num_workers: 1
refresh : True
start: True
is_main_worker: True
max_vote_delay_before_worker_restart: 20
max_restart_lag: 20
min_num_weights: 32
info_timeout: 5





