
model: opt1.3b
tokenizer: null
device: cuda
epoch_length: 100
finetune:
  num_layers: 4
max_allocation_ratio: 0.6 
optimizer:
  lr: 1.0e-05
  module: torch.optim.Adam
stats: {}
tag: null
test: True
load: false

