
model: opt1.3b
tokenizer: null
epoch_length: 10
save: true # save on epoch 
device: null
epoch_length: 100
max_allocation_ratio: 0.6 
finetune: 4
optimizer:
  lr: 1.0e-05
  module: torch.optim.Adam
stats: {}
buffer_ratio: 1.2
tag: null
test: True
load: false
device_map: auto

