

model: null
tag: base
device: null
device_map: auto
max_memory: null
trust_remote_code: True
finetune: 1
optimizer:
  lr: 2.0e-05
  module: torch.optim.Adam
load_in_8bit: False
max_sequence_length: 256
tag: null
load: false

shortcuts:
  oa.pythia.12b: OpenAssistant/oasst-sft-1-pythia-12b

  vicuna.33b : lmsys/vicuna-33b-v1.3
  vicuna.13b: lmsys/vicuna-13b-v1.3
  vicuna.7b: lmsys/vicuna-7b-v1.3

  llama: openlm-research/open_llama_7b
  
  llama2.70b: meta-llama/Llama-2-70b-chat-hf
  llama2.7b: meta-llama/Llama-2-7b

  llama13b: openlm-research/open_llama_13b
  llama-trl: trl-lib/llama-7b-se-rl-peft

  pygmalion-6b: Pygmalionreplit/replit-code-v1-3bAI/pygmalion-6b
  stablellm7b: StabilityAI/stablelm-tuned-alpha-7b
  mosaic: mosaicml/mpt-30b
  falcon_40b_instruct: tiiuae/falcon-40b-instruct
  falcon_uncensored: ehartford/WizardLM-Uncensored-Falcon-40b
  falcon: tiiuae/falcon-40b-instruct

  open_llama_13b: openlm-research/open_llama_13b
  lazarus30b: CalderaAI/30B-Lazarus
  # code
  starcoder: bigcode/starcoder
  wizardcoder: WizardLM/WizardCoder-15B-V1.0
  replit_code: replit/replit-code-v1-3b

block_prefix: model.layers
model2block_prefix:
  mosaic: transformer.blocks