
model: gpt125m
tag: base
tokenizer: null
save: true # save on epoch 
device: null
stats: null
device_map: auto
epoch_length: 500
accumulate_grad_batches: 1
patience_epochs: 10
best_epoch_loss_delta: 0.0
default_metric: 12
reset_stats: false
hidden_size: 768
vocab_size: 50258
loss_sigdigs: 3
max_gpu_ratio: 0.8
sample_history: 100
trust_remote_code: True
buffer_memory: 20gb
finetune: 1
optimizer:
  lr: 2.0e-05
  module: torch.optim.Adam
load_in_8bit: False
stats: {}
model_inflation_ratio: 1.5
output_length: 4
max_sequence_length: 256
clip_grad_norm: 1.0
tag: null
load: false
refresh_state: false
device_map: auto
max_memory: null
reserve_gpus: False
verbose: true
test: false
train: True
max_epochs_since_saved: 2
default_metric: 12
hidden_size: 768
vocab_size: 50258
loss_sigdigs: 3

shortcuts:
  gpt125m: EleutherAI/gpt-neo-125m
  gpt2.7b: EleutherAI/gpt-neo-2.7B
  gpt3b: EleutherAI/gpt-neo-2.7B
  opt1.3b: facebook/opt-1.3b
  opt2.7b: facebook/opt-2.7b
  gptjt: togethercomputer/GPT-JT-6B-v1
  gptjt_mod: togethercomputer/GPT-JT-Moderation-6B
  gptj: EleutherAI/gpt-j-6b
  gptj.pyg6b: PygmalionAI/pygmalion-6b
  gpt6b: cerebras/Cerebras-GPT-6.7B
  gptj.instruct: nlpcloud/instruct-gpt-j-fp16
  gptj.codegen: moyix/codegen-2B-mono-gptj
  gptj.hivemind: hivemind/gpt-j-6B-8bit
  gptj.adventure: KoboldAI/GPT-J-6B-Adventure
  gptj.pygppo: TehVenom/GPT-J-Pyg_PPO-6B
  gptj.alpaca.gpt4: vicgalle/gpt-j-6B-alpaca-gpt4
  gptj.alpaca: bertin-project/bertin-gpt-j-6B-alpaca
  oa.galactia.6.7b: OpenAssistant/galactica-6.7b-finetuned
  opt6.7b: facebook/opt-6.7b
  llama: openlm-research/open_llama_7b
  llama13b: openlm-research/open_llama_13b
  vicuna.13b: lmsys/vicuna-13b-delta-v0
  vicuna.7b: lmsys/vicuna-7b-delta-v0
  llama-trl: trl-lib/llama-7b-se-rl-peft
  opt.nerybus: KoboldAI/OPT-6.7B-Nerybus-Mix
  pygmalion-6b: PygmalionAI/pygmalion-6b
  falcon: tiiuae/falcon-40b-instruct
  oa.pythia.12b: OpenAssistant/oasst-sft-1-pythia-12b
  gptneox: EleutherAI/gpt-neox-20b
  gpt20b: EleutherAI/gpt-neox-20b
  opt13b: facebook/opt-13b
  gpt13b: cerebras/Cerebras-GPT-13B
  gptjvr: "~/models/gpt-j-6B-vR"
  stablellm7b: StabilityAI/stablelm-tuned-alpha-7b
  fish: "~/fish_model"
  vr: ~/models/gpt-j-6B-vR
  mosaic: mosaicml/mpt-30b
  falcon_40b_instruct: tiiuae/falcon-40b-instruct
  falcon_uncensored: ehartford/WizardLM-Uncensored-Falcon-40b
block_prefix: model.layers
model2block_prefix:
  mosaic: transformer.blocks
  
