name: PR and main Push Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Commune_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install curl nano python3 python3-dev python-is-python3 build-essential cargo libstd-rust-dev -y
          sudo python -m pip install --upgrade pip
          sudo pip install setuptools wheel
          sudo pip install -r requirements.txt
          sudo apt-get install -y nodejs npm
          sudo npm install -g pm2

      - name: Install Commune
        run: |
          sudo pip install -e .

      - name: Commune Tests - c sync
        run: c sync

      - name: Commune Tests - c balance
        run: c balance

      - name: Commune Tests - c demo serve tag=latest
        run: c demo serve tag=latest

      - name: Commune Tests - c root_key
        run: c root_key        

      - name: Commune Tests - c stats
        run: c stats  

      - name: Commune Tests - c modules
        run: c modules  

      # just hangs
      # - name: Commune Tests - c logs model.openai::whadup --lines 1
      #   run: c logs model.openai::whadup --lines 1
        
      - name: Commune Tests - c data.text.realfake test
        run: c data.text.realfake test

      - name: Commune Tests - c call data.text.realfake::whadup sample
        run: c call data.text.realfake::whadup sample
        
      - name: Commune Tests - c call data.text.truthqa::whadup sample
        run: c call data.text.truthqa::whadup sample

      - name: Commune Tests - c port_range
        run: c port_range        

# PLEASE PLEASE PLEASE ADD TESTS HERE

# Add create a docker image (to test building docker image for/with Commune)