
models: model.
network: global
update: True
tokenizer: gpt2
train: False
batch_size: 32
sequence_length: 256
dataset: dataset.bittensor
metric:  null
stats: {}
threshold: 4.0
max_stats_history: 100
namespace_update_interval: 100
alpha: 0.1
ma_keys: ['metric', 'weights']
ratio: 1.0
topk: 512 
load: False
new_loop_per_forward: True
hidden_size : 512


ensemble:
  Hot5: chest floor despair public hazard math extra gadget shrug coast pigeon help
  Hot6: feed lock connect liar pledge hill diagram elevator faculty survey parade yard
  Hot7: rookie famous resource type hand trial until protect jealous crawl valid wagon
  Hot8: invest iron lumber salon ostrich aware remember mind brief mammal enough fresh
  Hot9: bottom rebel hurry cushion humor vendor spoil clap loop shoe jump convince 